config/routes.rb
Rails.application.routes.draw do
  get 'inbox', to: 'inbox#index'

  resources :messages

  resources :premium_packages

  
  resources :relationships, only: [:create, :destroy]

  get 'contact', to: 'contact#index'
  get 'admin', to: 'admin#index'

  resources :enquiries

  resources :testimonials

  resources :businesses

  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'
  resources :users do
      member do
        get :following, :followers
      end
    end

end

app/models/business.rb
class Business < ActiveRecord::Base
	has_many :testimonials
	has_many :business_users
	has_many :users, through: :business_users
end

app/models/business_user.rb
class BusinessUser < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, class_name: "User"
	belongs_to :receiver, class_name: "User"
end

app/models/premium_package.rb
class PremiumPackage < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :testimonials
	has_one :premium_package
	has_one :profile
	has_many :business_users
	has_many :businesses, through: :business_users

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships

  has_many :messages, foreign_key: "sender_id", dependent: :destroy
  has_many :received_messages, foreign_key: "received_id", class_name: "Message", dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.profile = Profile.create(name: auth.info.name, image: auth.info.image)
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenicate_user!, only: :show
  
  def index
    @businesses = Business.all
    respond_with(@businesses)
  end

  def show
    respond_with(@business)
  end

  def new
    @business = Business.new
    respond_with(@business)
  end

  def edit
  end

  def create
    @business = Business.new(business_params)
    @business.save
    respond_with(@business)
  end

  def update
    @business.update(business_params)
    respond_with(@business)
  end

  def destroy
    @business.destroy
    respond_with(@business)
  end

  private
    def set_business
      @business = Business.find(params[:id])
    end

    def business_params
      params.require(:business).permit(:logo, :background_image, :name, :info, :street, :suburb, :postcode, :state, :country, :phone, :email, :twitter, :facebook, :linkedin, :latitude, :longitude)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inbox_helper.rb
module InboxHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/businesses/_form.html.erb
<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    	<%= f.input :logo, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :background_image, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :name, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :info, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :street, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :suburb, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :postcode, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :state, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :country, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :phone, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :email, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :twitter, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :facebook, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :linkedin, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :latitude, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :longitude, input_html: { class: 'form-control'} %>
    </div>
  

  <div class="form-actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses</h1>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Background image</th>
      <th>Name</th>
      <th>Info</th>
      <th>Street</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Country</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Twitter</th>
      <th>Facebook</th>
      <th>Linkedin</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.logo %></td>
        <td><%= business.background_image %></td>
        <td><%= business.name %></td>
        <td><%= business.info %></td>
        <td><%= business.street %></td>
        <td><%= business.suburb %></td>
        <td><%= business.postcode %></td>
        <td><%= business.state %></td>
        <td><%= business.country %></td>
        <td><%= business.phone %></td>
        <td><%= business.email %></td>
        <td><%= business.twitter %></td>
        <td><%= business.facebook %></td>
        <td><%= business.linkedin %></td>
        <td><%= business.latitude %></td>
        <td><%= business.longitude %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logo:</strong>
  <%= @business.logo %>
</p>

<p>
  <strong>Background image:</strong>
  <%= @business.background_image %>
</p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @business.info %>
</p>

<p>
  <strong>Street:</strong>
  <%= @business.street %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @business.suburb %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @business.postcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @business.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @business.country %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @business.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @business.email %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @business.twitter %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @business.facebook %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @business.linkedin %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @business.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @business.longitude %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>