config/routes.rb
Rails.application.routes.draw do
  get 'inbox', to: 'inbox#index'

  resources :messages

  resources :premium_packages

  
  resources :relationships, only: [:create, :destroy]

  get 'contact', to: 'contact#index'
  get 'admin', to: 'admin#index'

  resources :enquiries

  resources :testimonials

  resources :businesses

  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'
  resources :users do
      member do
        get :following, :followers
      end
    end

end

app/models/business.rb
class Business < ActiveRecord::Base
	has_many :testimonials
	has_many :business_users
	has_many :users, through: :business_users
end

app/models/business_user.rb
class BusinessUser < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, class_name: "User"
	belongs_to :receiver, class_name: "User"
end

app/models/premium_package.rb
class PremiumPackage < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :testimonials
	has_one :premium_package
	has_one :profile
	has_many :business_users
	has_many :businesses, through: :business_users

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships

  has_many :messages, foreign_key: "sender_id", dependent: :destroy
  has_many :received_messages, foreign_key: "received_id", class_name: "Message", dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.profile = Profile.create(name: auth.info.name, image: auth.info.image)
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  def index
  	@messages = Message.where('receiver_id = ?', current_user.id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  def index
    @profiles = Profile.all
    respond_with(@profiles)
  end

  def show
    respond_with(@profile)
  end

  def new
    @profile = Profile.new
    respond_with(@profile)
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.save
    respond_with(@profile)
  end

  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :image, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inbox_helper.rb
module InboxHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/profiles/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @profile.user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    	<%= f.input :name, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :image, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.association :user, input_html: { class: 'form-control'} %>
    </div>
  

  <div class="form-actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @profile.user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.image %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@profile.image) %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

<div class="col-md-4">

  <div class="stats">
    <a href="<%= following_user_path(@profile.user) %>" class="btn btn-lg btn-warning">
      <strong id="following" class="stat">
      Following 
        <span class="badge"><%= @profile.user.followed_users.count %></span> users
      </strong>

    </a>
    </p>
    <a href="<%= followers_user_path(@profile.user) %>" class="btn btn-lg btn-warning">
      <strong class="stat">
      Followed by
        <span class="badge" id="followers"><%= @profile.user.followers.count %></span> users
      </strong>

    </a>
  </div>
<br>
<div class="follow_unfollow">
<% unless current_user == @profile.user %>
  <div id="follow_form">
  <% if current_user.following?(@profile.user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>
</div>
</div>
</div>