config/routes.rb
Rails.application.routes.draw do
  get 'inbox', to: 'inbox#index'

  resources :messages

  resources :premium_packages

  
  resources :relationships, only: [:create, :destroy]

  get 'contact', to: 'contact#index'
  get 'admin', to: 'admin#index'

  resources :enquiries

  resources :testimonials

  resources :businesses

  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'
  resources :users do
      member do
        get :following, :followers
      end
    end

end

app/models/business.rb
class Business < ActiveRecord::Base
	has_many :testimonials
	has_many :business_users
	has_many :users, through: :business_users
end

app/models/business_user.rb
class BusinessUser < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :sender, class_name: "User"
	belongs_to :receiver, class_name: "User"
end

app/models/premium_package.rb
class PremiumPackage < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :testimonials
	has_one :premium_package
	has_one :profile
	has_many :business_users
	has_many :businesses, through: :business_users

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships

  has_many :messages, foreign_key: "sender_id", dependent: :destroy
  has_many :received_messages, foreign_key: "received_id", class_name: "Message", dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.profile = Profile.create(name: auth.info.name, image: auth.info.image)
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  def index
  	@messages = Message.where('receiver_id = ?', current_user.id)
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  def index
    @testimonials = Testimonial.all
    respond_with(@testimonials)
  end

  def show
    respond_with(@testimonial)
  end

  def new
    @testimonial = Testimonial.new
    respond_with(@testimonial)
  end

  def edit
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)
    @testimonial.save
    respond_with(@testimonial)
  end

  def update
    @testimonial.update(testimonial_params)
    respond_with(@testimonial)
  end

  def destroy
    @testimonial.destroy
    respond_with(@testimonial)
  end

  private
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    def testimonial_params
      params.require(:testimonial).permit(:star_rating, :review, :business_id, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inbox_helper.rb
module InboxHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= simple_form_for(@testimonial) do |f| %>
  <%= f.error_notification %>

  
  	<div class="form-group">
    	<%= f.input :star_rating, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.input :review, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.association :business, input_html: { class: 'form-control'} %>
    </div>
  	<div class="form-group">
    	<%= f.association :user, input_html: { class: 'form-control'} %>
    </div>
  

  <div class="form-actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<h1>Listing testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Star rating</th>
      <th>Review</th>
      <th>Business</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.star_rating %></td>
        <td><%= testimonial.review %></td>
        <td><%= testimonial.business %></td>
        <td><%= testimonial.user %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Star rating:</strong>
  <%= @testimonial.star_rating %>
</p>

<p>
  <strong>Review:</strong>
  <%= @testimonial.review %>
</p>

<p>
  <strong>Business:</strong>
  <%= @testimonial.business %>
</p>

<p>
  <strong>User:</strong>
  <%= @testimonial.user %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>